/* Generated By:JavaCC: Do not edit this line. BooleanQueryParserConstants.java */
package gmerg.model.BooleanQueryParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BooleanQueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int COLON = 6;
  /** RegularExpression Id. */
  int DOT = 7;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 8;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 9;
  /** RegularExpression Id. */
  int EXPRESSION = 10;
  /** RegularExpression Id. */
  int POSITION = 11;
  /** RegularExpression Id. */
  int TYPE = 12;
  /** RegularExpression Id. */
  int STAGE = 13;
  /** RegularExpression Id. */
  int PATTERN = 14;
  /** RegularExpression Id. */
  int LOCATION = 15;
  /** RegularExpression Id. */
  int OPERATOR = 16;
  /** RegularExpression Id. */
  int ORGAN = 18;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int OrganString = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\",\"",
    "\":\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "<EXPRESSION>",
    "<POSITION>",
    "<TYPE>",
    "<STAGE>",
    "<PATTERN>",
    "<LOCATION>",
    "<OPERATOR>",
    "\"\\\"\"",
    "\"\\\"\"",
    "<token of kind 19>",
  };

}
